# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d6ca77f6858e7d9653e4f97114413daebd3ff62c008948fe8b7f0c17ce17ade2ae5bfbfdddbf28341108e81dd9a36f9f003468524c0818d5f3eb51e9de3ac53

test:
  secret_key_base: fc0d64573d78dbc8b1e39838406ebee23592ec96b66a7f67f77286c02e2d6b582c7b28fe34ae20320babd4864843cbd821c9cc263732a67ee44587f13910bb09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
